### ISSUE TITLE
Auto Potion & Mega Macro

### ISSUE THREAD

**Issue by privacymonk3y** [ollidiemaus/AutoPotion#40]
Hey there,

I really love Auto Potion and would like to use it but I'm also using [Mega Macro](https://www.curseforge.com/wow/addons/mega-macro). The problem being that for some reason every time Auto Potion generates a updated Macro it just keeps spamming a new macro rather then over writing the current one.

This might be something more on the Mega Macro side but the developer isn't currently playing and I'm learning lua atm but not enough to investigate it thoroughly. Is there anything that can be done to bring these two great addons together?

**Comment by phuze** [comment]
Addons like AutoPotion interact with the game's default macro API by using global functions such as `CreateMacro` and `EditMacro`. These functions rely on macro names for identification.

MegaMacro, however, manages macros through its own system, using random IDs in place of the traditional names. As a result, when an addon like AutoPotion attempts to modify a macro named "AutoPotion," it can't locate it. This causes the addon to continually create new macros, leading to an infinite number being generated.

Ideally, MegaMacro should be redesigned to allow other addons to interface with the game's native macro system without issues. At the very least, it should provide public hooks that enable third-party addon developers to perform basic CRUD (create, read, update, delete) operations on macros by name. Since MegaMacro stores the macro names as DisplayName in its internal table, this should be achievable.

That said, it's still possible to implement compatibility with MegaMacro. I will submit a PR shortly which aims to add support for MegaMacro.

**Comment by ollidiemaus** [comment]
this should be fixed with #53 but im not a fan of mega macro this seems way to hacky if every addons which uses macros like blizzard attempted them to will break ALL your macros just because of Mega Macro.

**Comment by phuze** [comment]
Thank you for merging these changes.

> but im not a fan of mega macro

To the project’s credit, Mega Macro’s interface is a big step up from Blizzard’s default. One of the best features is how it lets you organize and scope macros by Global, Class, Spec, and Character -- something I’ve come to rely on. After getting used to how flexible and easy it is to manage macros with Mega Macro, I really don’t think I could go back to Blizzard’s built-in system.

![image](https://github.com/user-attachments/assets/581b1778-d457-4876-900c-93c5741b10de)

That said, I agree there are some issues with how the system is implemented. It blocks other addons from interfacing with macros in the way Blizzard originally intended. This approach can be problematic, and creates a bit of a “foot gun” scenario -- players could unknowingly take actions that leave their macros disorganized or broken.

I plan to contribute to the Mega Macro project to address these concerns. My goals include improving macro safety, ensuring smoother transitions between Mega Macro and the default Blizzard macro system, and fostering better compatibility with other addons in the community. I believe there’s a lot of potential here.
